### ISSUE TITLE
[REQUEST/MISSING] Differential/delta downloads not implemented

### ISSUE THREAD

**Issue by Riccorbypro** [Official-Husko/NN-Downloader#1]
**Is your feature request related to a problem? Please describe.**
I see in the `config.json` that there is an option for `oneTimeDownload`, defaulted to `true`. There is no documentation around this, but I'd assume that if you turn `oneTimeDownload` to `false` then your downloads should become differential. In other words, if you download a tag that has 20 posts today, and tomorrow it has 25 (of which you already have 20), then re-running that download should only download the 5 posts that are missing.

Looking through the code, this does not seem to be implemented in any of the downloaders, and is only read from the config file in `main.py`.

**Describe the solution you'd like**
The `oneTimeDownload` feature should be implemented as described above.

**Describe alternatives you've considered**
It is easy enough to simply merge previously downloaded folders together for specific tag sets, however this causes multiple downloads of the same post, and therefore unnecessary requests to the site's API.

**Additional context**
This was tested on e621, but should also be non-functional on all other sites as the feature is simply not implemented.

**Site URL**
N/A

**Does the site have an API?**
N/A

**Comment by Official-Husko** [comment]
If both of us are not wrong then that feature is really missing yes. I think i put that there and forgot to implement it. I will push an update that fixes it in a couple of days

**Comment by Official-Husko** [comment]
I have added the oneTimeDownload feature for E621 and E926. If you feel this completes this ticket then please close it. If not please clarify what i missed in the update.

**Comment by Riccorbypro** [comment]
Ah yes, the good old "small missing feature causes moderate refactor of the entire system".

Looks good for this feature, but I have spotted an issue in the auto updater. I'll log a second issue for that though as its more related to the new feature rather than a missing one.
