### ISSUE TITLE
Tag downloads for AI training

### ISSUE THREAD

**Issue by Nechochwen-D** [Official-Husko/NN-Downloader#12]
Would it be possible to add an option to download the tags associated with an image, possibly to a /metadata/[date]_[time]_[tags]/ directory?

**Comment by Official-Husko** [comment]
I a bit confused on what you mean exactly. Do you have an example? A folder layout or whatever might make my monkey brain understand this.

**Comment by Nechochwen-D** [comment]
Something like this,
![image](https://github.com/Official-Husko/NN-Downloader/assets/20625980/a3858b33-9238-4b01-81d5-67817ffe9066)
[4593278.json](https://github.com/Official-Husko/NN-Downloader/files/14234595/4593278.json)

**Comment by Official-Husko** [comment]
should be doable sure. I will take a look into it later today to see what i can do

**Comment by Official-Husko** [comment]
@Nechochwen-D I have a test build ready. Please give it a shot and if it fulfills your needs tag me so i can release the update publicly as a full build.
[NN-Downloader-EXPERIMENTAL.zip](https://github.com/Official-Husko/NN-Downloader/files/14290813/NN-Downloader-EXPERIMENTAL.zip)

**Comment by Nechochwen-D** [comment]
I am getting an error message.

```Traceback (most recent call last):
  File "/home/user/NN-Downloader/main.py", line 1, in <module>
    from modules import *
  File "/home/user/NN-Downloader/modules/__init__.py", line 1, in <module>
    from .proxyScraper import ProxyScraper
ModuleNotFoundError: No module named 'modules.proxyScraper'

**Comment by Nechochwen-D** [comment]
The compiled version seems to work through wine however. And the file layout works just fine too.

**Comment by Nechochwen-D** [comment]
@Official-Husko I think there is an issue with the capitalization's of the files being called not matching. You may want to take a look at that.

**Comment by Nechochwen-D** [comment]
[edited.zip](https://github.com/Official-Husko/NN-Downloader/files/14292394/edited.zip)
This seems to work for me. I manually merged the changes from your dev branch to the files I got from the master branch.

**Comment by Nechochwen-D** [comment]
Thanks.
