### ISSUE TITLE
[BUG] cannot access local variable 'meta_tags'

### ISSUE THREAD

**Issue by KayJay95** [Official-Husko/NN-Downloader#16]
**Describe the bug**
I tried running the tag "tail" for E621 and got the error:
"[!] An error occured while downloading from e621! Please report this. Exception: cannot access local variable 'meta_tags' where it is not associated with a value"
Persists even when running the .exe as administrator

Tbh Idk how you'd reproduce it, I downloaded the .exe and after I ran it, set up the API etc. just couldn't download

**Screenshots**
![image](https://github.com/Official-Husko/NN-Downloader/assets/159560575/96c4ddfe-a6af-446a-b358-8b781093cfa6)

**Desktop:**
 - OS: Windows
 - Version 11

**Tool:**
- Site: e621
- Tool Version: 1.6.0
- Tags/Link: tail

I have to say that I am in no way a coder nor know anything about this. I already struggled with the API settings 😅

**Runtime Log**
[runtime.log](https://github.com/Official-Husko/NN-Downloader/files/14300133/runtime.log)

Thanks in advance

**Comment by Official-Husko** [comment]
damnit looks like i fucked up something. I will push a fix in a few minutes

**Comment by Official-Husko** [comment]
@KayJay95 Do me a favor and try this build. If it solves the issue you had you can close this issue.
[NN-Downloader.zip](https://github.com/Official-Husko/NN-Downloader/files/14300331/NN-Downloader.zip)

**Comment by KayJay95** [comment]
@Official-Husko Yep, seems to work fine now, thanks :D

**Comment by Official-Husko** [comment]
Thank you for your report and enjoy the tool!
