### ISSUE TITLE
[BUG] Auto updater never recognises that its up to date

### ISSUE THREAD

**Issue by Riccorbypro** [Official-Husko/NN-Downloader#2]
**Describe the bug**
When using the auto updater, the update applies correctly. However, the auto updater still shows the application as outdated.

**To Reproduce**
- Launch and configure the latest release of NNDownloader (1.4.0 at time of writing)
- The auto updater will prompt you to download the "latest version"
- Update to this version and relaunch NNDownloader
- The auto updater still prompts to update

**Expected behavior**
The auto updater should not prompt you to update when you are on the latest version

**Screenshots**
![image](https://github.com/Official-Husko/NN-Downloader/assets/13792979/da635c73-416a-4cef-8923-063d8e464718)

**Used Parameters and Settings (please complete the following information):**
N/A

**Additional context**
I believe this issue is caused by a mismatch between the versioning provided by the GitHub API and checking against the version in the config file. I did try to modify the config version to `1.4.0`, however this is not valid JSON as the version is currently stored as `float`.

This is from a quick glance through the code though and could be completely wrong - I'm not familiar with python.

**Comment by Official-Husko** [comment]
god damnit.

**Comment by Official-Husko** [comment]
The issue *should* be fixed. Please run it again and let it update and report back if it still wants to act funny.

PS: turns out it was a simple `=` that i forgot to remove.

**Comment by Official-Husko** [comment]
I consider this issue resolved. If you encounter the bug again comment on the issue and i will reopen it.
