### ISSUE TITLE
[BUG] Error Message

### ISSUE THREAD

**Issue by Official-Husko** [Official-Husko/NN-Downloader#29]
### Discussed in https://github.com/Official-Husko/NN-Downloader/discussions/28

<div type='discussions-op-text'>

<sup>Originally posted by **Sakumaid111** May  3, 2024</sup>
Hi i'm getting an Error message but can't tell why i'm getting this 

"An error occured while downloading from e621! Please report this. Exception: 'posts'"</div>

**Comment by Official-Husko** [comment]
@Sakumaid111 Just to clarify you can't download anything currently right?

**Comment by Sakumaid111** [comment]
Yes same message everytime ^^ (sorry for the late response)

**Comment by Official-Husko** [comment]
> Yes same message everytime ^^ (sorry for the late response)

For me it works without issues. Can you share what you entered and your config? Just replace the actual api key with "API_KEY_HERE" or something like that.

**Comment by Sakumaid111** [comment]
give me two min first time using github sorry ^^

**Comment by Sakumaid111** [comment]
![Error](https://github.com/Official-Husko/NN-Downloader/assets/168864996/b311f891-05f6-4ecb-8fad-2bb3867b131e)
![Config](https://github.com/Official-Husko/NN-Downloader/assets/168864996/704dc7bd-e6c5-433f-b69a-7aae8e62c6f9)

I think that's what you wanted and sorry if i'm taking your time for nothing probably, never used something like that ^^

**Comment by Official-Husko** [comment]
> ![Error](https://private-user-images.githubusercontent.com/168864996/327904972-b311f891-05f6-4ecb-8fad-2bb3867b131e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3ODMxNDUsIm5iZiI6MTcxNDc4Mjg0NSwicGF0aCI6Ii8xNjg4NjQ5OTYvMzI3OTA0OTcyLWIzMTFmODkxLTA1ZjYtNGVjYi04ZmFkLTJiYjM4NjdiMTMxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQwMDM0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGJiODJhMDBlOTY2YzM4NzQ5NzlkZDRjZTI4ZGQ3NzFkNGQ3YzBlZDcwNGJjMzg5Y2ZiYjhmZTY3MWY0YjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._fd-UbwGeIB3oHn0_bt0jwUvmXYJzmXReDy19msBPXw) ![Config](https://private-user-images.githubusercontent.com/168864996/327904974-704dc7bd-e6c5-433f-b69a-7aae8e62c6f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3ODMxNDUsIm5iZiI6MTcxNDc4Mjg0NSwicGF0aCI6Ii8xNjg4NjQ5OTYvMzI3OTA0OTc0LTcwNGRjN2JkLWU2YzUtNDMzZi1iNjlhLTdhYWU4ZTYyYzZmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQwMDM0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGU3ZDM0MmZiMzljMjg0M2UxZjc0YWJlOGRkYzE3ODFiMjU2NzI3YzZlNzZjMjJhYTU3YzJkOThkMjY1YzllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OF1MprCw5VkZP_0T3wBtngzTFt4rA2SeAjdPI5wA_Eg)
> 
> I think that's what you wanted and sorry if i'm taking your time for nothing probably, never used something like that ^^

is that your actual api key in the image or a placeholder?

**Comment by Sakumaid111** [comment]
yep it is i got it in "account" > "Manage API Access" i think that's where i'm supposed to take it

**Comment by Official-Husko** [comment]
> yep it is i got it in "account" > "Manage API Access" i think that's where i'm supposed to take it

I have edited the comment to remove the api key with the image. Avoid sending the actual api keys to other people or publicly on the internet next time please. The mistake was that you put the api key in both fields. top is username and bottom for the actual key. Additionally please revoke your current api key and generate a new one.

**Comment by Sakumaid111** [comment]
oh okay damn my bad i legit don't know what that thing is used for

**Comment by Official-Husko** [comment]
> oh okay damn my bad i legit don't know what that thing is used for

No problem mistakes happen and luckily we fix it instantly. With the api key depending on the platform it can access all your data and even control your account. This can range from simple liking images to deleting the account in some cases so always keep it private and secure.

**Comment by Official-Husko** [comment]
here is an example on how the config should look if you did it all correctly:

```json
            "e621": {
                  "apiUser": "YOUR_E621_USERNAME_HERE",
                  "apiKey": "YOUR_API_KEY_HERE"
            },
```

So in my case for example:

```json
            "e621": {
                  "apiUser": "Official Husko",
                  "apiKey": "asidhasiudghasiudhgasasdadasdassadsad"
            },
````

**Comment by Sakumaid111** [comment]
Yep it's working sorry for taking your time for just that simple mistake ^^

And thanks for telling me what that Api key is for and fixing my problem, have a good day... or night i don't know :3

**Comment by Official-Husko** [comment]
> Yep it's working sorry for taking your time for just that simple mistake ^^
> 
> And thanks for telling me what that Api key is for and fixing my problem, have a good day... or night i don't know :3

No problem always happy to help. And a good day to you too or night. In my case night at 3 am in the morning ..

![gif](https://media1.tenor.com/m/BFlbDfl8iBEAAAAC/fall-asleep-falling-asleep.gif)
