### ISSUE TITLE
[BUG] Any tag on E621

### ISSUE THREAD

**Issue by xhizor420** [Official-Husko/NN-Downloader#3]
**To Reproduce**
Launch and configure the latest release of NNDownloader (1.4.2 at time of writing)

**Expected behavior**
I type in a tag like "animated" and I get 
Downloading |⚠︎                                       | (!) 0/320 [0%] in 0.8s (0.00/s)
[!] An error occured while downloading from e621! Please report this. Exception: cannot access local variable 'safe_user_tags' where it is not associated with a value

Any tag I type it doesn't work.

**Screenshots**
![EdPQHQa](https://github.com/Official-Husko/NN-Downloader/assets/135182224/57b0f5ad-4704-48b3-88b0-8528c8deeeb1)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Used Parameters and Settings (please complete the following information):**
- Site: e621
- Tool Version: NN
- Tags/Link: animated

### ***Please attach the runtime.log***
[runtime.log](https://github.com/Official-Husko/NN-Downloader/files/12500089/runtime.log)

**Comment by Official-Husko** [comment]
Well this is a weird issue. It only happens on the compiled source but not when launching it directly using python on the local machine.

**Comment by Official-Husko** [comment]
Issue has been resolved in [v1.4.3](https://github.com/Official-Husko/NN-Downloader/releases/tag/1.4.3). Update the tool using the inbuilt auto-updater or download it again manually.

**Comment by Official-Husko** [comment]
I consider this issue resolved. If you encounter the bug again comment on the issue and i will reopen it.
