### ISSUE TITLE
[BUG] Folder Name Length causing crash

### ISSUE THREAD

**Issue by KayJay95** [Official-Husko/NN-Downloader#38]
**The Bug**
If you run the Downloader with tags longer than 256 char it breaks as the output folder name cant be longer then that.

**Error**
[WinError 123] The filename, directory name, or volume label syntax is incorrect: 'media/22-06-2024_12-52-58_-vore_-death_-flash_-fart_-nipple_vore_-breast_expansion_-vore_pov_-unbirthing_-pooping_-body_size_growth_-urine_-soiling_-muscular_-big_breasts_-big_penis_-thick_thighs_de4dm1lk_fleurfurr_lettuce_artist_kind_lurker_ssevisx_81yffulfmm_noxxlss_ruffruffles_lintwave_4hazelstreet_uricomics_dudles_codyblue-731_100racs_replicant_skrunkle_lemonbird_rilesthecat_entom_kyufuru_lyonley_slashkill_domibun_lilmoonie'

**To Reproduce**
1. Run the Downloader
2. Select e621
3. Type in any tags as long as they are, in total, longer than 256 characters

**Expected behavior**
Downloader should run normally (maybe allow users to name output folders / change them, as planned in #31)

**Screenshot**
![image](https://github.com/Official-Husko/NN-Downloader/assets/159560575/ed6c0077-0b1f-4b96-8629-0334f1f96e62)

**Desktop**:
 - OS: Windows
 - Version 11

**Used Parameters and Settings**:
- Site: e621
- Tool Version: v.1.6.3
- Tags/Link (EXAMPLE): -vore -death -flash -fart -nipple_vore -breast_expansion -vore_pov -unbirthing -pooping -body_size_growth -urine -soiling -muscular -big_breasts -big_penis -thick_thighs ~de4dm1lk ~fleurfurr ~lettuce_(artist) ~kind_lurker ~ssevisx ~81yffulfmm ~noxxlss ~ruffruffles ~lintwave ~4hazelstreet ~uricomics ~dudles ~codyblue-731 ~100racs ~replicant_skrunkle ~lemonbird ~rilesthecat ~entom ~kyufuru ~lyonley ~slashkill ~domibun ~lilmoonie

**runtime.log**
[runtime.log](https://github.com/user-attachments/files/15936270/runtime.log)

**Comment by Official-Husko** [comment]
god damnit, i knew this would come around to bite me in the ass. I will push a quick fix to address the issue.

**Comment by Official-Husko** [comment]
Is it possible that the tags you provided have no results? While testing to see if the issue was resolved i saw that there are no results with these tags.

**Comment by Official-Husko** [comment]
@KayJay95 do me a favor and try this build. If it works i can fully release it.

[Download](https://github.com/Official-Husko/NN-Downloader/actions/runs/9626323699/artifacts/1627686873)

**Comment by KayJay95** [comment]
@Official-Husko Sorry it took me this long to respond, yes the version works perfectly, thank you :D 👍 
![image](https://github.com/Official-Husko/NN-Downloader/assets/159560575/29788a82-36b1-449a-873b-d9f3bd2433e7)
