### ISSUE TITLE
[BUG] There is an issue with the pages setting in Rule 34

### ISSUE THREAD

**Issue by Akemi-Madoka** [Official-Husko/NN-Downloader#42]
Select rule34 and enter tags
blue_archive+pregnant
**bad！**
![image](https://github.com/user-attachments/assets/9abaf774-02ed-4833-a063-602f0ba2cc8d)

Manually using API
https://api.rule34.xxx/index.php?page=dapi&s=post&q=index&pid=1&limit=100&json=1&tags=blue_archive+pregnant
**ok！**

**and！**

https://api.rule34.xxx/index.php?page=dapi&s=post&q=index&pid=1&limit=1000&json=1&tags=blue_archive+pregnant
**bad！**
https://api.rule34.xxx/index.php?page=dapi&s=post&q=index&pid=0&limit=1000&json=1&tags=blue_archive+pregnant
**ok！**

Then check the source code
![image](https://github.com/user-attachments/assets/f0905c2f-f6d4-4307-bff2-c69a0aab5a73)

I think the page parameter of rule34 should start from 0.
The current mechanism causes any number of tags less than 1000 to be zero

**Comment by Official-Husko** [comment]
God damnit. Thank you for the report. i will solve this tomorrow once I'm back from work.

**Comment by Official-Husko** [comment]
After some testing the issue seems to be that you added a "+" between tag 1 and 2. If removed it works fine.
Additionally the tags you provided with the "+" doesn't work using the manual api endpoints. Try it without that and report back the status please.

**Comment by Official-Husko** [comment]
@Akemi-Madoka Try this build and see if it fixes your issue. Additionally as said above do not include the + in your tags.
[nn-downloader-windows.zip](https://github.com/user-attachments/files/16325657/nn-downloader-windows.zip)

**Comment by Akemi-Madoka** [comment]
> After some testing the issue seems to be that you added a "+" between tag 1 and 2. If removed it works fine. Additionally the tags you provided with the "+" doesn't work using the manual api endpoints. Try it without that and report back the status please.

There is no problem with '+'

https://api.rule34.xxx/index.php?page=dapi&s=post&q=index&pid=0&limit=1000&json=1&tags=blue_archive+pregnant
num **367**

https://api.rule34.xxx/index.php?page=dapi&s=post&q=index&pid=0&limit=1000&json=1&tags=blue_archive%20pregnant
num **367**

https://api.rule34.xxx/index.php?page=dapi&s=post&q=index&pid=1&limit=1000&json=1&tags=blue_archive+pregnant
num **0**

https://api.rule34.xxx/index.php?page=dapi&s=post&q=index&pid=1&limit=1000&json=1&tags=blue_archive%20pregnant
num **0**

**Comment by Akemi-Madoka** [comment]
> @Akemi-Madoka Try this build and see if it fixes your issue. Additionally as said above do not include the + in your tags. [nn-downloader-windows.zip](https://github.com/user-attachments/files/16325657/nn-downloader-windows.zip)

![image](https://github.com/user-attachments/assets/4078b8ca-d61c-421e-a76c-b5d44abc8d2f)

**good!**

Although the quantity seems to be a little more..
Perhaps it's because there are configured exclusion items in my browser cookie

**Comment by Akemi-Madoka** [comment]
> @Akemi-Madoka尝试此版本，看看它是否能解决您的问题。此外，如上所述，不要在标签中包含 +。nn [-downloader-windows.zip](https://github.com/user-attachments/files/16325657/nn-downloader-windows.zip)

sorry, Frequent occurrence of the following problems：
![image](https://github.com/user-attachments/assets/6a97c3bb-0eb3-437b-badd-894434a05124)
[!] An error occured while downloading from rule34! Please report this. Exception: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2559)

This may not have much to do with the previous issue, but I still hope that this problem can be resolved..
Perhaps it's a version issue with OpenSSL?

**Comment by Official-Husko** [comment]
> > @Akemi-Madoka尝试此版本，看看它是否能解决您的问题。此外，如上所述，不要在标签中包含 +。nn [-downloader-windows.zip](https://github.com/user-attachments/files/16325657/nn-downloader-windows.zip)
> 
> sorry, Frequent occurrence of the following problems： ![image](https://private-user-images.githubusercontent.com/38621390/351048539-6a97c3bb-0eb3-437b-badd-894434a05124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODE1NzgsIm5iZiI6MTcyMTY4MTI3OCwicGF0aCI6Ii8zODYyMTM5MC8zNTEwNDg1MzktNmE5N2MzYmItMGViMy00MzdiLWJhZGQtODk0NDM0YTA1MTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIwNDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NDRmODU5ZGMyYzMwMDc0NTI2YmRjMjMwMzBmY2Q3MGU5ZjMyN2NlNDI0YmZmYTczMTQzMTFjNDAyZmJhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QEG27EGk8lOwZE0wniZTs17YEz6vtKpQ13gXiCP6OX0) [!] An error occured while downloading from rule34! Please report this. Exception: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2559)
> 
> This may not have much to do with the previous issue, but I still hope that this problem can be resolved.. Perhaps it's a version issue with OpenSSL?

I have never encountered an ssl issue with any of my projects. Are you using any proxies? either in the tool itself with the inbuilt function or a third party proxy.

**Comment by Akemi-Madoka** [comment]
> > > @Akemi-Madoka尝试此版本，看看它是否能解决您的问题。此外，如上所述，不要在标签中包含 +。nn [-downloader-windows.zip](https://github.com/user-attachments/files/16325657/nn-downloader-windows.zip)
> > 
> > 
> > sorry, Frequent occurrence of the following problems： ![image](https://private-user-images.githubusercontent.com/38621390/351048539-6a97c3bb-0eb3-437b-badd-894434a05124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODE1NzgsIm5iZiI6MTcyMTY4MTI3OCwicGF0aCI6Ii8zODYyMTM5MC8zNTEwNDg1MzktNmE5N2MzYmItMGViMy00MzdiLWJhZGQtODk0NDM0YTA1MTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIwNDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NDRmODU5ZGMyYzMwMDc0NTI2YmRjMjMwMzBmY2Q3MGU5ZjMyN2NlNDI0YmZmYTczMTQzMTFjNDAyZmJhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QEG27EGk8lOwZE0wniZTs17YEz6vtKpQ13gXiCP6OX0) [!] An error occured while downloading from rule34! Please report this. Exception: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2559)
> > This may not have much to do with the previous issue, but I still hope that this problem can be resolved.. Perhaps it's a version issue with OpenSSL?
> 
> I have never encountered an ssl issue with any of my projects. Are you using any proxies? either in the tool itself with the inbuilt function or a third party proxy.

yes,I am using a network proxy, otherwise I cannot access rule34.
Perhaps this issue is not particularly important, as there is an R34Downloader as an alternative...

**Comment by Official-Husko** [comment]
> > > > @Akemi-Madoka尝试此版本，看看它是否能解决您的问题。此外，如上所述，不要在标签中包含 +。nn [-downloader-windows.zip](https://github.com/user-attachments/files/16325657/nn-downloader-windows.zip)
> > > 
> > > 
> > > sorry, Frequent occurrence of the following problems： ![image](https://private-user-images.githubusercontent.com/38621390/351048539-6a97c3bb-0eb3-437b-badd-894434a05124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODE1NzgsIm5iZiI6MTcyMTY4MTI3OCwicGF0aCI6Ii8zODYyMTM5MC8zNTEwNDg1MzktNmE5N2MzYmItMGViMy00MzdiLWJhZGQtODk0NDM0YTA1MTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIwNDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NDRmODU5ZGMyYzMwMDc0NTI2YmRjMjMwMzBmY2Q3MGU5ZjMyN2NlNDI0YmZmYTczMTQzMTFjNDAyZmJhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QEG27EGk8lOwZE0wniZTs17YEz6vtKpQ13gXiCP6OX0) [!] An error occured while downloading from rule34! Please report this. Exception: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2559)
> > > This may not have much to do with the previous issue, but I still hope that this problem can be resolved.. Perhaps it's a version issue with OpenSSL?
> > 
> > I have never encountered an ssl issue with any of my projects. Are you using any proxies? either in the tool itself with the inbuilt function or a third party proxy.
> 
> yes,I am using a network proxy, otherwise I cannot access rule34.
> Perhaps this issue is not particularly important, as there is an R34Downloader as an alternative...

If you are using a third party proxy then please make sure to disable the inbuilt proxy system. Additionally maybe try to use the unbuilt ones with your external one disabled.

**Comment by Official-Husko** [comment]
Has this issue been resolved? If so please close it.

**Comment by thejason-bugged** [comment]
I do not have as much information to give, but I had the exact same issue with any combo of tags

anything plus Jade_Harley isn't working, and doesn't load, examples used were searching Jade_Harely Jade_Harley futanari and Jade_Harley angstrom 

I am behind no proxies or marks of the sort, but using the version you posted in this issue did fix my problem and let them download no problem.

**Comment by Official-Husko** [comment]
> I do not have as much information to give, but I had the exact same issue with any combo of tags
> 
> anything plus Jade_Harley isn't working, and doesn't load, examples used were searching Jade_Harely Jade_Harley futanari and Jade_Harley angstrom
> 
> I am behind no proxies or marks of the sort, but using the version you posted in this issue did fix my problem and let them download no problem.

So you had the same issue but the latest update has fixed it?
