### ISSUE TITLE
[REQUEST] Add content tags in the file name

### ISSUE THREAD

**Issue by jqiu07** [Official-Husko/NN-Downloader#43]
Welcome, hope you're doing well.

**Is your feature request related to a problem? Please describe.**
No issue, honestly enjoying it. Just wished the software gave the images/videos every single tag that they have.

**Describe the solution you'd like**
As of right now, content is hard to organize without proper tagging. I know the folders that contain the content have tags, but that's usually only a few (usually for me not too sure if that's anybody else) and not every single tag that the image has. Now I'm not too sure if the API's allow this, but if possible it would make organization much easier. I propose that putting tags in the file name would be best, such as "ID tag1 tag2 tag3 tag4...", as this would also allow the default file explorer search function to work.

**Describe alternatives you've considered**
I have maybe thought of doing it myself, looping through the directory and getting the ID of the image/video, getting the JSON/HTML then getting the tags through that and adding it to the file name, but haven't gotten around to doing it.

**Additional context**
As for the reason I am requesting this, I am attempting to archive e621, r34, e926, etc. content, so this feature would make organization and search for content much easier.

**Site URL**
Not a site request.

**Does the site have an API?**
N/A

![image](https://github.com/user-attachments/assets/9536b7b9-2b68-4ebc-b59d-2fc3d6a34e01)

**Comment by Official-Husko** [comment]
Greetings!

This certainly is possible but the issue is that with a certain amount of tags will create issues with the file names where they will become too long. I can look into it but are you sure there are no other solutions? maybe add the tags into the file info like description or something like that or maybe using a second file for the image that stores all the site data (pretty mich ai training mode). If needed i could surely help with a small tool that sorts it all for you using these json data files for each image.

**Comment by jqiu07** [comment]
I appreciate your quick response. I was cooked when I posted this request since it was late at night, so I didn't have the brainpower to come up with good alternatives. But I didn't even realize that the meta folder within the downloaded folder contained JSON files with all the tags, which was a huge oversight from me. I think I'm going to save you some work and add the tags to the image EXIF metadata myself. I could use the coding practice anyway.

**Comment by Official-Husko** [comment]
Alright sounds good. Heads up tho i think "ai training" currently only works for e sites so i would have to update it for r34 and such if you need that.

**Comment by Official-Husko** [comment]
> I appreciate your quick response. I was cooked when I posted this request since it was late at night, so I didn't have the brainpower to come up with good alternatives. But I didn't even realize that the meta folder within the downloaded folder contained JSON files with all the tags, which was a huge oversight from me. I think I'm going to save you some work and add the tags to the image EXIF metadata myself. I could use the coding practice anyway.

Do you want to keep this issue open or can i close it for now?

**Comment by jqiu07** [comment]
You can close this issue.
