### ISSUE TITLE
[BUG] Errno 13 permission denied when trying to download a fav: tag

### ISSUE THREAD

**Issue by masuteri** [Official-Husko/NN-Downloader#5]
Errno 13 when trying to download fav:masuteri tag

**To Reproduce**
1. run the app for the first time
2. Set the blacklists to [], put in api key and name and save
3. Run it again, choose e621 and as the tag fav:masuteri with pagecount left empty
4. Observe

**Expected behavior**
All media should get downloaded

**Screenshots**
![kuva](https://github.com/Official-Husko/NN-Downloader/assets/80328342/0d770e1d-af00-40d3-b7d4-ebc10878d5c8)

**Desktop**
 - OS: Windows
 - Version 11

**Used Parameters and Settings (please complete the following information):**
- Site: e621
- Tool Version: 1.4.3
- Tags/Link: fav:masuteri

[runtime.log](https://github.com/Official-Husko/NN-Downloader/files/13182826/runtime.log)

**Comment by Official-Husko** [comment]
It looks like its not allowed to access the database file. Try running it in administrator mode and see if it works. Depending on where you stored the tool this issue might appear. Where is it located exactly?

**Comment by masuteri** [comment]
It's located on the desktop and yep there's a file called like that with a size of 1kb

**Comment by Official-Husko** [comment]
> It's located on the desktop and yep there's a file called like that with a size of 1kb

did you try to run it as admin?

**Comment by masuteri** [comment]
Running it on desktop as an admin in its dedicated folder didn't work, but moving the folder inside downloads worked without admin.

**Comment by Official-Husko** [comment]
> Running it on desktop as an admin in its dedicated folder didn't work, but moving the folder inside downloads worked without admin.

glad to hear you got it working. it somehow got blocked in the process then. I will add an additional safety net in the next update that informs the user if read & write permission is missing. If you consider this issue resolved please close it.
