### ISSUE TITLE
E6AI support [REQUEST] 

### ISSUE THREAD

**Issue by JoThePony** [Official-Husko/NN-Downloader#7]
**Describe the solution you'd like**
I would love to see this site added as i think the API is similar if not the same to e621

**Site URL**
https://e6ai.net/

**Does the site have an API?**
Yes, https://e6ai.net/help/api

**Comment by Official-Husko** [comment]
Sure thing! I will check it out tomorrow.

**Comment by Official-Husko** [comment]
Support has been added in version [1.5.0](https://github.com/Official-Husko/NN-Downloader/commit/b7debd44ba2c001f92811dcb31f6194eaea7973f). If you already have NN-Downloader feel free to use the inbuilt auto updater, alternately get it from [here](https://github.com/Official-Husko/NN-Downloader/releases/latest).
